name: github pages

on:
  push:
    branches:
      - www  # Set a branch name to trigger deployment

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install doxygen
          python3 -m venv env
          source env/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Build docs
        run: |
          source env/bin/activate
          make html
          echo -n enzyme.mit.edu > ./build/html/CNAME

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
